[project]
name = "orders-microservice-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "woozlic", email = "sampaccs@mail.ru" }
]
requires-python = ">=3.12"
dependencies = [
    "celery[redis]>=5.6.3",
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
orders-microservice-fastapi = "orders_microservice_fastapi:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
